import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}  style={{display :"flex" , placeItems : "center"  , flexDirection : 'column' , height :"100%" , gap: 20}}>
        <h1 style={{
          borderWidth : 2, borderColor:"red" , borderStyle:"solid"
        }}>Hey I&apos;m Layout Component 🖐</h1>
        <div style={{display :"flex" , placeItems : "center"  , flexDirection : 'column' , height :"100%" , gap: 20}}>

          {children}
          
        </div>
      </body>
    </html>
  )
}
